<<<<<<< HEAD
title: 锦辰的刻版画
email: iigrow@outlook.com
description: 
    精致的雕刻刀，朴素的刻板，塑印沉淀的知识，相信自己，你可以的。
baseurl: ""
url: "http://iigrow.com" 
github_username:  iigrow
markdown: kramdown
=======
title: 锦辰的一亩三分地
email: iigrow@outlook.com
description: 
baseurl: ""
url: "http://iigrow.com" 
github_username:  iigrow
markdown: kramdown
>>>>>>> f7c5b3a1ba63dcc804cfef442cf850809405953d
